# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyopencode < Formula
  desc "Terminal UI for managing opencode sessions"
  homepage "https://github.com/actionscripted/lazyopencode"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.3.0/lazyopencode_0.3.0_darwin_amd64.tar.gz"
      sha256 "4f9d27657e4da69a6dc98723b0b360405336bbb3d7ddd0bd83e4416d59a6107f"

      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.3.0/lazyopencode_0.3.0_darwin_arm64.tar.gz"
      sha256 "4922aeb146ae9955e6ac06939e97dc45d420d49a5b1587bcb9883f3bd505b6cc"

      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.3.0/lazyopencode_0.3.0_linux_amd64.tar.gz"
      sha256 "248aca6062f45c16852cb61bdcafd6c986c717d8b62945099dd931a3d3e938e4"
      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.3.0/lazyopencode_0.3.0_linux_arm64.tar.gz"
      sha256 "f84cd01ae6f432be8076b01a3e9b7f361225e3ac9eb24aa6bdd207cc9edf6402"
      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazyopencode --version")
  end
end
