# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyopencode < Formula
  desc "Terminal UI for managing opencode sessions"
  homepage "https://github.com/actionscripted/lazyopencode"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.2.1/lazyopencode_0.2.1_darwin_amd64.tar.gz"
      sha256 "30861008a9a56fdd55d44dd44bf759430db4f1eca2eb7b955276bdde1edc7864"

      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.2.1/lazyopencode_0.2.1_darwin_arm64.tar.gz"
      sha256 "8acc5d59551d262994f26f080a48a4e3c370cf8716e33a2287f68f0ce6721275"

      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.2.1/lazyopencode_0.2.1_linux_amd64.tar.gz"
      sha256 "8354a21a716a94726e47897c3762c07aa0d35b78369b57317e43fa05446c564c"
      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.2.1/lazyopencode_0.2.1_linux_arm64.tar.gz"
      sha256 "5891fecdf02889a9a7df3c4777932ae5970cb7c8487fe2ed3246202228e8fe5a"
      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazyopencode --version")
  end
end
