# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyopencode < Formula
  desc "Terminal UI for managing opencode sessions"
  homepage "https://github.com/actionscripted/lazyopencode"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.3.1/lazyopencode_0.3.1_darwin_amd64.tar.gz"
      sha256 "ef1de8e4004b9f435d2782b86df1e7215533bf23fd76338131c3a05213ae16f4"

      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.3.1/lazyopencode_0.3.1_darwin_arm64.tar.gz"
      sha256 "8e17c09b3e5acec401d18c24500c8ba9a125c5bdb61574826957fad2d31ceab6"

      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.3.1/lazyopencode_0.3.1_linux_amd64.tar.gz"
      sha256 "ebe6e4cd793e4543f69dc92a0d60358ae9a56add44ca59e856c7e05db93985d1"
      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ActionScripted/lazyopencode/releases/download/v0.3.1/lazyopencode_0.3.1_linux_arm64.tar.gz"
      sha256 "9145420ee023299850e9d49094fd2673ece00f7b8fad939db983bfde518e755a"
      define_method(:install) do
        bin.install "lazyopencode"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazyopencode --version")
  end
end
